### ISSUE TITLE
v2.2.0 not working for me

### ISSUE THREAD

**Issue by richardkall** [middleman/middleman-autoprefixer#11]
I just tried v2.2.0 but none of my prefixes are generated. When downgrading to v2.1.2 everything is back to normal. Do I need to configure something differently with the new version?

**config.rb:**

``` ruby
activate :autoprefixer do |config|
  config.browsers = ['last 5 versions', 'Explorer >= 9']
end
```

**CSS:**

``` css
a {
  transition: transform 1s;
}
```

**Output in v2.1.2**:

``` css
a {
  -webkit-transition: -webkit-transform 1s;
  transition: transform 1s;
}
```

**Output in v2.2.0**:

``` css
a {
  transition: transform 1s;
}
```
